version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - docker.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
